#!/bin/bash

ACTION=$1
SERVER=$2
SOURCE=$(dirname $(readlink -f $0))

# Verify first parameter exists (action)
if [ -f $ACTION ]
then
  echo "First parameter required (list|benchmark|build|start|info|stop|clean)"
  exit
fi

# Run actions that don't require server parameter
case $ACTION in
  "list")
    cd $SOURCE/servers
    for d in $(ls -dR */**); do echo $d; done
    exit;;

  "benchmark")
    docker run --rm --net="host" \
      williamyeh/wrk \
      -t1 -c11 -d11s --timeout 1s \
      http://127.0.0.1:8888/api/echo/HelloWorld?num=1234567890
    exit;;

  "test")
    HAPPY_TEST=$(curl -s localhost:8888/api/echo/HelloWorld?num=1234567890)
    if [[ $HAPPY_TEST == "{\"message\":"* ]]
    then
      printf "HappyTest-PASS, "
    else
      printf "HappyTest-FAIL, "
      printf "$HAPPY_TEST, "
    fi

    ERROR_TEST=$(curl -s localhost:8888/api/echo/GoodbyeWorld?num=321)
    if [[ $ERROR_TEST == "{\"error\":\"Invalid parameters\"}" ]]
    then
      printf "ErrorTest-PASS\n"
    else
      printf "ErrorTest-FAIL, "
      printf "$ERROR_TEST\n"
    fi

    exit;;
esac

# Verify second parameter exists (server/directory)
if [ -f $SERVER ]
then
  echo "Second parameter required (ex: go/go)"
  exit
fi

# cd to server directory
cd $SOURCE/servers/$SERVER

# Docker image name
SUFFIX=${SERVER//\//-} # Convert / to -
NAME=httpbench-$SUFFIX

# Run server action
case $ACTION in
  "build")
    docker build --rm -t $NAME .
    ;;
  "start")
    docker run -dt --rm --name=$NAME --net="host" $NAME
    ;;
  "start-int")
    docker run -it --rm --name=$NAME --net="host" $NAME
    ;;
  "start-dev")
    docker run -it --rm --name=$NAME --net="host" -v ${PWD}:/app $NAME sh
    ;;
  "info")
    docker exec $NAME sh info
    ;;
  "stop")
    docker kill $NAME
    docker rm --force $NAME
    ;;
  "clean")
    docker rmi --force $NAME
    ;;
esac
